CREATE TABLE cards (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    set_id INTEGER references sets(id),
    scryfall_id TEXT NOT NULL,
    card_name TEXT NOT NULL,
    cost TEXT,
    card_type TEXT,
    color TEXT, -- colors TEXT = "W|U|B|R|G" --- Leave empty for colorless
    rarity TEXT,
    image_url TEXT NOT NULL
);